import { SummaryGenerator } from "@/components/summary-generator";

export default function SummarizerPage() {
  return (
    <div className="container py-12">
      <div className="space-y-4 mb-12 text-center">
        <h1 className="text-4xl font-headline tracking-tighter sm:text-5xl">AI Meeting Summarizer</h1>
        <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
          Paste your meeting transcript below to get a concise summary generated by AI.
        </p>
      </div>
      <SummaryGenerator />
    </div>
  );
}
